<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Too many failed attempts_VfPpkd-muHVF_8ead10</name>
   <tag></tag>
   <elementGuidId>01b9105f-4f79-4f96-8478-f5e1041e17a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.VfPpkd-muHVFf-bMcfAe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78ebd4d4-aa23-4414-8fb7-af47e1cba969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-muHVFf-bMcfAe</value>
      <webElementGuid>e7a59f06-241a-46f2-bfff-7658d82952e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1bd53145-2e7f-42a2-88c3-440e24a7083b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>YPqjbf</value>
      <webElementGuid>909c64ac-8e74-4b32-9fed-5593f4662ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>focus:AHmuwe; blur:O22p3e;change:WPi0i;</value>
      <webElementGuid>b4f56f89-e204-4d09-b472-5d8a6ab13cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>selectionc1</value>
      <webElementGuid>464baaed-fa4d-4cb9-b0a0-b7a4db81a531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;g98c7c&quot;]/div[@class=&quot;aDGQwe&quot;]/div[@class=&quot;eKnrVb&quot;]/div[@class=&quot;CYBold&quot;]/div[@class=&quot;j663ec&quot;]/div[@class=&quot;tCpFMc&quot;]/form[1]/span[1]/section[@class=&quot;aTzEhb&quot;]/div[@class=&quot;CxRgyd&quot;]/div[@class=&quot;VBGMK&quot;]/div[@class=&quot;SdBahf Fjk18&quot;]/div[@class=&quot;EcjFDf&quot;]/div[@class=&quot;IhH7Wd&quot;]/div[@class=&quot;ci67pc&quot;]/div[@class=&quot;BudEQ rBUW7e&quot;]/div[@class=&quot;sSzDje NEk0Ve&quot;]/div[@class=&quot;enBDyd&quot;]/div[@class=&quot;VfPpkd-MPu53c VfPpkd-MPu53c-OWXEXe-dgl2Hf Ne8lhe swXlm az2ine y5MMGc sD2Hod VfPpkd-MPu53c-OWXEXe-mWPk3d VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d-OWXEXe-AHe6Kc-XpnDCe VfPpkd-ksKsZd-mWPk3d VfPpkd-ksKsZd-mWPk3d-OWXEXe-ZNMTqd&quot;]/input[@class=&quot;VfPpkd-muHVFf-bMcfAe&quot;]</value>
      <webElementGuid>38947b89-922f-4611-80fa-a12d831343cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>4287143d-b6c8-445e-8b95-0e459f6dbb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/div/div[2]/div/div/div/form/span/section[2]/div/div/div/div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>74eba5f9-2288-4f78-b96e-67bf7ec8ae47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>d39ac23f-0eec-4fa5-a57f-78d1f679bd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>99455595-5c0e-4e33-b935-48b5a4016f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
